### ISSUE TITLE
Completely empty YAML file results in error about destructuring null

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo#193]
If a pipeline.yml file contains no contents at all (in this case, it only contained a lengthy comment), then the following error is given and monofo _crashes_!

```
TypeError: Cannot destructure property 'monorepo' of 'js_yaml_1.load(...)' as it is null.
    at Function.read (/var/lib/buildkite-agent/.npm/_npx/7612/lib/node_modules/monofo/build/src/config.js:167:17)
    at async Promise.all (index 4)
    at async Function.readAll (/var/lib/buildkite-agent/.npm/_npx/7612/lib/node_modules/monofo/build/src/config.js:229:17)
    at async Function.getAll (/var/lib/buildkite-agent/.npm/_npx/7612/lib/node_modules/monofo/build/src/config.js:237:25)
```

**Comment by dominics** [comment]
Fixed @ 83fe31c0df347de263932f909c4e84d650bdad49
